// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string           `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string           `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              []*Model_Address `protobuf:"bytes,5,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Model) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Model) GetAddress() []*Model_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Model_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model_Address) Reset()         { *m = Model_Address{} }
func (m *Model_Address) String() string { return proto.CompactTextString(m) }
func (*Model_Address) ProtoMessage()    {}
func (*Model_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

func (m *Model_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model_Address.Unmarshal(m, b)
}
func (m *Model_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model_Address.Marshal(b, m, deterministic)
}
func (m *Model_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model_Address.Merge(m, src)
}
func (m *Model_Address) XXX_Size() int {
	return xxx_messageInfo_Model_Address.Size(m)
}
func (m *Model_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Model_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Model_Address proto.InternalMessageInfo

func (m *Model_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Model_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Model_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Model_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// Handler Request
type GetRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type FindRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRequest struct {
	User                 *Model   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *Model {
	if m != nil {
		return m.User
	}
	return nil
}

// Handler Response
type GetResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Users                []*Model `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetResponse) GetUsers() []*Model {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FindResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User                 *Model   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FindResponse) GetUser() *Model {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "user.Model")
	proto.RegisterType((*Model_Address)(nil), "user.Model.Address")
	proto.RegisterType((*GetRequest)(nil), "user.GetRequest")
	proto.RegisterType((*FindRequest)(nil), "user.FindRequest")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*GetResponse)(nil), "user.GetResponse")
	proto.RegisterType((*FindResponse)(nil), "user.FindResponse")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x7d, 0x49, 0x93, 0xa6, 0xef, 0xe6, 0xbd, 0xa2, 0x63, 0x91, 0x21, 0x20, 0xd6, 0x2c, 0xa4,
	0x1b, 0x8b, 0xb6, 0x2b, 0x97, 0x2a, 0xd8, 0x95, 0x9b, 0x40, 0xb7, 0x42, 0x6c, 0x2e, 0x1a, 0x6c,
	0x33, 0x75, 0x66, 0x82, 0xf4, 0x93, 0xfc, 0x38, 0xff, 0x41, 0xe6, 0x4e, 0xc6, 0xa6, 0x82, 0x74,
	0x37, 0xe7, 0xe4, 0xdc, 0x9c, 0x73, 0x6e, 0x26, 0x00, 0xb5, 0x42, 0x39, 0x5e, 0x4b, 0xa1, 0x05,
	0x0b, 0xcc, 0x39, 0xfd, 0xf4, 0x20, 0x7c, 0x10, 0x05, 0x2e, 0x59, 0x1f, 0xfc, 0xb2, 0xe0, 0xde,
	0xd0, 0x1b, 0xfd, 0xcd, 0xfc, 0xb2, 0x60, 0x0c, 0x82, 0x2a, 0x5f, 0x21, 0xf7, 0x89, 0xa1, 0x33,
	0x1b, 0x40, 0x88, 0xab, 0xbc, 0x5c, 0xf2, 0x0e, 0x91, 0x16, 0x18, 0x76, 0xfd, 0x22, 0x2a, 0xe4,
	0x81, 0x65, 0x09, 0xb0, 0x0b, 0x88, 0xf2, 0xa2, 0x90, 0xa8, 0x14, 0x0f, 0x87, 0x9d, 0x51, 0x3c,
	0x39, 0x1a, 0x93, 0x3b, 0xb9, 0x8d, 0x6f, 0xec, 0xa3, 0xcc, 0x69, 0x12, 0x84, 0xa8, 0xe1, 0xd8,
	0x31, 0x74, 0x95, 0x96, 0x88, 0xba, 0x49, 0xd3, 0x20, 0x93, 0x68, 0x51, 0xea, 0x8d, 0x4b, 0x64,
	0xce, 0xc6, 0x5b, 0xe9, 0x5c, 0xa3, 0x4b, 0x44, 0x80, 0x71, 0x88, 0x16, 0xa2, 0xae, 0xb4, 0xdc,
	0x34, 0x99, 0x1c, 0x4c, 0xcf, 0x01, 0x66, 0xa8, 0x33, 0x7c, 0xab, 0x51, 0x69, 0xa3, 0x7b, 0xc5,
	0xcd, 0xbb, 0x90, 0xae, 0xb8, 0x83, 0xe9, 0x09, 0xc4, 0xf7, 0x65, 0x55, 0x38, 0xe1, 0x8f, 0xe5,
	0xa4, 0x97, 0xf0, 0xff, 0x4e, 0x62, 0xae, 0xd1, 0x09, 0x4e, 0x81, 0xf6, 0x49, 0x92, 0x78, 0x12,
	0xb7, 0xaa, 0x66, 0x76, 0xd1, 0x8f, 0x10, 0x93, 0xb1, 0x5a, 0x8b, 0x4a, 0xa1, 0xed, 0x98, 0xeb,
	0x5a, 0x6d, 0x3b, 0x1a, 0xc4, 0xce, 0x20, 0x34, 0x72, 0xc5, 0x7d, 0xda, 0xd9, 0xce, 0x8b, 0xec,
	0x13, 0x53, 0x99, 0xda, 0x50, 0xe5, 0x30, 0xb3, 0x20, 0x9d, 0xc1, 0x3f, 0x1b, 0x78, 0x8f, 0x81,
	0x0b, 0xea, 0xff, 0x16, 0xf4, 0x16, 0xfa, 0xae, 0xda, 0x9e, 0x57, 0x71, 0x88, 0x56, 0xa8, 0x54,
	0xfe, 0xec, 0x2e, 0x89, 0x83, 0x93, 0x0f, 0x0f, 0x82, 0xb9, 0x42, 0xc9, 0xae, 0xa0, 0x37, 0x43,
	0x3d, 0xa7, 0xdc, 0x07, 0xd6, 0x6b, 0xbb, 0xfe, 0xe4, 0xb0, 0xc5, 0x58, 0xaf, 0xf4, 0x0f, 0x9b,
	0x42, 0xcf, 0x14, 0xa1, 0xf1, 0x46, 0xd0, 0xfa, 0x12, 0x09, 0x6b, 0x53, 0xdf, 0x43, 0xd7, 0x00,
	0x36, 0x34, 0x8d, 0x35, 0x37, 0x6d, 0xe7, 0x0b, 0x25, 0x83, 0x5d, 0xd2, 0x8d, 0x3e, 0x75, 0xe9,
	0x77, 0x98, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x12, 0x43, 0x49, 0xf1, 0x1c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	FindUser(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	CreateUser(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.User/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindUser(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.User/FindUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/user.User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUsers(context.Context, *GetRequest) (*GetResponse, error)
	FindUser(context.Context, *FindRequest) (*FindResponse, error)
	CreateUser(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUsers(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedUserServer) FindUser(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUser not implemented")
}
func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUsers(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindUser(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _User_GetUsers_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _User_FindUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
